# Generated by Django 6.0.1 on 2026-02-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_taskcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='annual_leave_days',
            field=models.PositiveIntegerField(default=28),
        ),
    ]
