# Generated by Django 6.0.1 on 2026-02-23 06:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_annual_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calendar_feed_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
