from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),              # momentan e pagina de signup
    path('search-user/', views.search_user, name='search_user'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('signup/', views.signup, name='signup'),
    path('team/', views.team, name='team'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks/export/csv/', views.export_tasks_csv, name='export_tasks_csv'),
    path('tasks/<int:task_id>/export/csv/', views.export_task_csv, name='export_task_csv'),
    path('submissions/admin/', views.submissions_admin, name='submissions_admin'),
    path('tasks/<int:task_id>/submit/', views.add_submission, name='add_submission'),
    path('tasks/<int:task_id>/submission/', views.see_submission, name='see_submission'),
    path('api/notifications/', views.notifications_api, name='notifications_api'),
    path('api/notifications/mark/', views.notifications_mark, name='notifications_mark'),
    path('api/bot/', views.bot_api, name='bot_api'),
    path('api/bot/history/', views.bot_history_api, name='bot_history_api'),
    path('calendar/', views.calendar_worker, name='calendar'),
    path('calendar/sync/regenerate/', views.regenerate_calendar_feed_token, name='regenerate_calendar_feed_token'),
    path('calendar/sync/<uuid:token>.ics', views.calendar_feed_ics, name='calendar_feed_ics'),
    path('calendar/google/connect/', views.google_calendar_connect, name='google_calendar_connect'),
    path('calendar/google/callback/', views.google_calendar_callback, name='google_calendar_callback'),
    path('calendar/google/disconnect/', views.google_calendar_disconnect, name='google_calendar_disconnect'),
    path('calendar/info/', views.calendar_info_worker, name='calendar_info_worker'),
    path('calendar/info-admin/', views.calendar_info_admin, name='calendar_info_admin'),
    path('calendar/info-admin/', views.calendar_info_admin, name='calendar_info_admin'),
    path('calendar/request/', views.calendar_request_worker, name='calendar_request_worker'),
    path('calendar/requests/', views.calendar_holiday_requests_admin, name='calendar_holiday_requests_admin'),
    path('calendar/requests/export/csv/', views.export_holiday_requests_csv, name='export_holiday_requests_csv'),
    path('calendar/current-holidays/', views.calendar_current_holidays_admin, name='calendar_current_holidays_admin'),
    path('profile/', views.profile, name='profile'),
    path('team/member/<int:user_id>/', views.profile_public, name='profile_public'),
    path('logout/', views.logout_user, name='logout'),
    path('chat/presence/', views.chat_presence_api, name='chat_presence_api'),
    path('chat/', views.chat, name='chat'),
    path('meetings/add/', views.add_meeting, name='add_meeting'),
    path('meetings/<int:meeting_id>/delete/', views.delete_meeting, name='delete_meeting'),
]
